apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangotodos
  labels:
    app: djangotodos
    app.kubernetes.io/part-of: django-todo-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: '3.12'
    app.kubernetes.io/name: 'djangotodos'
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"db"}]'
    app.openshift.io/vcs-uri: 'https://github.com/jkeam/djangotodos.git'
    app.openshift.io/vcs-ref: 'main'
spec:
  selector:
    matchLabels:
      app: djangotodos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: djangotodos
    spec:
      containers:
      - name: djangotodos
        image: quay.io/jkeam/djangotodos
        imagePullPolicy: Always
        env:
        - name: APP_MODE
          value: "simple"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: DEBUG
          value: "True"
        - name: SECRET_KEY
          value: "django-insecure-#zd522dfd9)ce1j4*-lj%t@r$syze#@+$(9j89td=@+t8d)!k+"
        - name: DB_NAME
          value: "todos"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "adminpassword"
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: CSRF_TRUSTED_ORIGINS
          value: "*"
        ports:
        - containerPort: 8000
          name: theport
        command: ["/bin/sh"]
        args: ["-c", "python ./manage.py runserver 0.0.0.0:8000"]
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 2
          periodSeconds: 2
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 10
      restartPolicy: Always
