apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangotodos
  labels:
    app: djangotodos
spec:
  selector:
    matchLabels:
      app: djangotodos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: djangotodos
    spec:
      containers:
        - image: IMAGE
          name: djangotodos
          ports:
          - containerPort: 8080
            name: theport
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: djangotodos
  labels:
    app: djangotodos
spec:
  ports:
    - name: port8000
      port: 8080
      targetPort: 8080
  selector:
    app: djangotodos
  type: LoadBalancer

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: djangotodos
  labels:
    app: djangotodos
spec:
  path: /
  to:
    kind: Service
    name: djangotodos
    weight: 100
  port:
    targetPort: port8000
