apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: registry.redhat.io/rhel9/postgresql-16:9.6-1751360823
          name: db
          env:
          - name: POSTGRESQL_USER
            value: todouser
          - name: POSTGRESQL_PASSWORD
            value: todopassword
          - name: POSTGRESQL_ADMIN_PASSWORD
            value: adminpassword
          - name: POSTGRESQL_DATABASE
            value: todos
          ports:
          - containerPort: 5432
            name: theport
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/pgsql/data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db
