# Generated by Django 5.0.1 on 2024-08-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='todos.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='horizon',
            field=models.CharField(choices=[('AC', 'Action'), ('PR', 'Project'), ('FO', 'Focus'), ('GO', 'Goal'), ('VI', 'Vision'), ('PU', 'Purpose')], default='AC', max_length=2),
        ),
    ]
