# Generated by Django 5.0.1 on 2024-08-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.CharField(choices=[('BA', 'Backlog'), ('PL', 'Planned'), ('IP', 'InProgress')], default='BA', max_length=2),
        ),
    ]
