apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

images:
- name: quay.io/jkeam/djangotodos
  digest: sha256:74f70f1561c18abaec86a18b627905e0cd7189a6bfdb68347bf92a45bf7a3327

resources:
  - namespace.yaml
  - db
  - app
